version: "2"
services:
    explorer:
        build:
          context: ./explorer/
          dockerfile: Dockerfile
        volumes:
          - ./backend:/usr/local/lib/python3.6/site-packages/backend:ro
          - ./explorer/notebooks:/home/jovyan/work/notebooks/:rw
        command: bash -c "start-notebook.sh --NotebookApp.token=''"
        env_file:
          - .env
        ports:
          - 8888:8888
        environment:
          - PYTHONPATH=/home/jovyan/work

    backend:
        build:
          context: ./backend
          dockerfile: Dockerfile
        volumes:
          # App files and config
          - ./backend/config/uwsgi.ini:/app/uwsgi.ini:ro
          - ./backend/config/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
          - ./backend/app/main.py:/app/main.py:ro
          # Library
          - ./backend:/usr/local/lib/python3.6/site-packages/backend:ro
          # Data
          - ./data/:/app/data/:ro
          # Runners
          - ./runners/:/app/runners:ro
          # Linters and Tests
          - ./backend/tests/:/app/tests:ro
          - .flake8:/app/.flake8:ro
          - ./backend/lib/:/app/lib:ro
        environment:
          - POSTGRES_URL=$POSTGRES_URL
        env_file:
          - .env
        ports:
          - 8080:8080

    frontend:
        build:
          context: ./frontend
          dockerfile: Dockerfile
        volumes:
          - .env:/usr/src/app/tds-frontend/.env:ro
        env_file:
          - .env
        ports:
          - 8081:8081
          - 80:8081
