version: "2"
services:
    explorer:
        build:
          context: ./models/explorer
          dockerfile: Dockerfile
        volumes:
          - ./:/home/jovyan/work:rw
          - ./models/:/usr/local/lib/python3.6/site-packages/network-adequacy:ro
          - ./web-app/backend:/usr/local/lib/python3.6/site-packages/backend:ro
          - ./web-app/backend:/home/jovyan/work/backend:ro
        command: bash -c "start-notebook.sh --NotebookApp.token=''"
        env_file:
          - .env
        ports:
          - 8888:8888
        environment:
          - PYTHONPATH=/home/jovyan/work

    backend:
        build:
          context: ./web-app/backend
          dockerfile: Dockerfile
        volumes:
          - ./web-app/backend/app/main.py:/app/main.py:ro
          - ./web-app/backend/lib/:/app/lib/:ro
          - ./web-app/backend/config/uwsgi.ini:/app/uwsgi.ini:ro
          - ./web-app/backend/config/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
          - ./web-app/backend/tests:/app/tests:ro
          - ./web-app/backend/app/:/var/local/app/:ro
          - .flake8:/app/.flake8:ro
          - ./web-app/backend:/usr/local/lib/python3.6/site-packages/backend
        environment:
          - POSTGRES_URL=$POSTGRES_URL
        env_file:
          - .env
        ports:
          - 8080:8080
