version: "2"

volumes:
  postgres-data:
    driver: local

services:

    backend:
      depends_on:
        - db
      links:
        # Link with the DB container as `db.local`.
        - db:db.local
      volumes:
        - ./backend/config/entrypoint-local.sh:/entrypoint.sh:ro
      ports:
        - 8082:8080

    frontend:
      ports:
        - 8083:8081
      environment:
        - API_ROOT=http://localhost:8082

    db:
      image: mdillon/postgis
      ports:
        # Expose port for convenient local access.
        - 5432:5432
      volumes:
        - postgres-data:/var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: example
        POSTGRES_DB: network_adequacy
